name: Deploy to VPS on Tag

on:
  push:
    tags:
      - "v*.*.*" # Dispara quando uma tag no formato v1.0.0 for criada
      - "release-*" # Ou tags no formato release-*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.18.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Build project
        run: pnpm run build
        env:
          PUPPETEER_ARGS: --no-sandbox --disable-setuid-sandbox

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            # Navegar para o diretório do projeto
            cd /var/www/larbac

            # Fazer backup da versão atual
            sudo cp -r . ../backup-$(date +%Y%m%d-%H%M%S) 2>/dev/null || true

            # Configurar PATH para Node.js e pnpm
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            
            # Instalar pnpm se não estiver instalado
            if ! command -v pnpm &> /dev/null; then
              curl -fsSL https://get.pnpm.io/install.sh | sh -
              export PNPM_HOME="$HOME/.local/share/pnpm"
              export PATH="$PNPM_HOME:$PATH"
            fi

            # Resetar mudanças locais e fazer pull das mudanças
            sudo git fetch --all
            sudo git reset --hard HEAD
            sudo git clean -fd
            sudo git checkout ${{ github.ref_name }}

            # Configurar PATH completo para sudo
            NODE_PATH=$(which node)
            PNPM_PATH=$(which pnpm)
            FULL_PATH="$(dirname $NODE_PATH):$(dirname $PNPM_PATH):$PATH"

            # Instalar dependências e fazer build
            sudo -E env PATH="$FULL_PATH" pnpm install --frozen-lockfile
            sudo -E env PATH="$FULL_PATH" pnpm run build

            # Copiar arquivos buildados para o diretório web
            sudo cp -r dist/* . 2>/dev/null || echo "Nenhum arquivo dist encontrado"

            # Reiniciar nginx se estiver ativo
            if systemctl is-active --quiet nginx; then
              sudo systemctl reload nginx
            else
              echo "Nginx não está ativo, pulando reload"
            fi

            echo "Deploy da tag ${{ github.ref_name }} concluído!"

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Deploy realizado com sucesso!"
          echo "Tag: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Falha no deploy!"
          echo "Tag: ${{ github.ref_name }}"
          echo "Verifique os logs para mais detalhes."
