name: Deploy to VPS on Tag

on:
  push:
    tags:
      - "v*.*.*" # Dispara quando uma tag no formato v1.0.0 for criada
      - "release-*" # Ou tags no formato release-*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.18.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Build project
        run: pnpm run build
        env:
          PUPPETEER_ARGS: --no-sandbox --disable-setuid-sandbox

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            # Navegar para o diretório do projeto
            cd /var/www/larbac

            # Fazer backup da versão atual
            sudo cp -r . ../backup-$(date +%Y%m%d-%H%M%S)

            # Fazer pull das mudanças
            sudo git fetch --all
            sudo git checkout ${{ github.ref_name }}

            # Instalar dependências e fazer build
            sudo pnpm install --frozen-lockfile
            sudo pnpm run build

            # Copiar arquivos buildados para o diretório web
            sudo cp -r dist/* .

            # Reiniciar nginx (se necessário)
            sudo systemctl reload nginx

            echo "Deploy da tag ${{ github.ref_name }} concluído!"

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Deploy realizado com sucesso!"
          echo "Tag: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Falha no deploy!"
          echo "Tag: ${{ github.ref_name }}"
          echo "Verifique os logs para mais detalhes."
